client
dev tun
proto udp
remote 172.16.96.50 1194
ca ca.crt
cert /etc/openvpn/client1.crt
key /etc/openvpn/client1.key
tls-crypt ta.key 1
#persist-key
#persist-tun
verb 1
cipher AES-256-GCM
auth SHA512
remote-cert-tls server
mssfix 1200
reneg-sec 0
#auth-nocache






