-- BTC_Staging
DELETE FROM BTC_Staging.dbo.STG_TX_INPUTS
DELETE FROM BTC_Staging.dbo.STG_TX_OUTPUTS
DELETE FROM BTC_Staging.dbo.STG_TRANSACTIONS
DELETE FROM BTC_Staging.dbo.STG_BLOCKS
DELETE FROM BTC_Staging.dbo.STG_FEAR_GREED_RAW
DELETE FROM BTC_Staging.dbo.STG_MARKET_DAILY
DELETE FROM BTC_Staging.dbo.STG_PIPELINE_LOG

-- BTC_DW
DELETE FROM BTC_DW.dbo.FACT_TRANSACTION
DELETE FROM BTC_DW.dbo.ERR_QUALITY_REJECTS
DELETE FROM BTC_DW.dbo.DIM_BLOCK
DELETE FROM BTC_DW.dbo.DIM_TX_TYPE
DELETE FROM BTC_DW.dbo.DIM_MARKET
DELETE FROM BTC_DW.dbo.DIM_DATE