[sources.ext_sql_database]
credentials="mssql+pymssql://sbiuser:sbipass@156.17.130.187:22433/AdventureWorks2014"

[sources.local_sql_database.credentials]
drivername = "mssql+pymssql"
username = "sa"
password = "YourStrong!Pass123@sqlserver"
host = "sqlserver"
port = 1433
database = "AdventureWorks"

[destination.local_mssql]
destination_type = "mssql"

[destination.local_mssql.credentials]
drivername = "mssql+pymssql" # dialect + driver
database = "AWStaging"
username = "sa"
password = "YourStrong!Pass123"
host = "sqlserver" # matches docker-compose service name
port = 1433
connect_timeout = 30

[destination.local_mssql.credentials.query]
TrustServerCertificate = "yes"
Encrypt = "yes"