
load("C:/Users/uo299874/Desktop/RComander/Steel.RData")
library(abind, pos=16)
local({
  .Table <- xtabs(~breakdowns+temperature, data=Steel)
  cat("\nFrequency table:\n")
  print(.Table)
  .Test <- chisq.test(.Table, correct=FALSE)
  print(.Test)
})
local({
  .Table <- xtabs(~breakdowns+temperature, data=Steel)
  cat("\nFrequency table:\n")
  print(.Table)
  .Test <- chisq.test(.Table, correct=FALSE)
  print(.Test)
  cat("\nExpected counts:\n")
  print(.Test$expected)
})
local({
  .Table <- xtabs(~breakdowns+temperature, data=Steel)
  cat("\nFrequency table:\n")
  print(.Table)
  .Test <- chisq.test(.Table, correct=FALSE)
  print(.Test)
  cat("\nExpected counts:\n")
  print(.Test$expected)
  cat("\nChi-square components:\n")
  print(round(.Test$residuals^2, 2))
})
local({
  .Table <- xtabs(~breakdowns+temperature, data=Steel)
  cat("\nFrequency table:\n")
  print(.Table)
  cat("\nTotal percentages:\n")
  print(totPercents(.Table))
  .Test <- chisq.test(.Table, correct=FALSE)
  print(.Test)
  cat("\nExpected counts:\n")
  print(.Test$expected)
  cat("\nChi-square components:\n")
  print(round(.Test$residuals^2, 2))
})
.Table <- matrix(c(4,5,12,9,8,8,8,2), 2, 4, byrow=TRUE)
dimnames(.Table) <- list("rows"=c("Gno", "Gob"), "columns"=c("0", "1", "2", "3"))
.Table  # Counts
.Test <- chisq.test(.Table, correct=FALSE)
.Test
remove(.Test)
remove(.Table)
with(Steel, cor.test(CO, CO2, alternative="two.sided", method="pearson"))
cor(Steel[,c("CO2","consumption")], use="complete")
with(Steel, cor.test(CO2, consumption, alternative="two.sided", method="pearson"))
local({
  .Table <- xtabs(~system+temperature, data=Steel)
  cat("\nFrequency table:\n")
  print(.Table)
  .Test <- chisq.test(.Table, correct=FALSE)
  print(.Test)
})
local({
  .Table <- xtabs(~system+temperature, data=Steel)
  cat("\nFrequency table:\n")
  print(.Table)
  cat("\nTotal percentages:\n")
  print(totPercents(.Table))
  .Test <- chisq.test(.Table, correct=FALSE)
  print(.Test)
})

