%% Ex 1:
% Define the function
syms x;
f = x^3 * exp(-x^2);

% Step A: Finding Zeros and Asymptotes
zeros_f = solve(f,x);
limit(f,x,-inf);
limit(f,x,inf);

% Step B: Local Maxima and Minima, Increasing and Decreasing Intervals
f_1 = diff(f);
zeros_f_1 = double(solve(f_1,x));
double(subs(f_1,x,-2));
double(subs(f_1,x,-1));
double(subs(f_1,x,1));
double(subs(f_1,x,2));

double(subs(f,x,solve(f_1,x)));

% Step C: Analyzing Concavity
f_2 = diff(f_1);
zeros_f_2 = double(solve(f_2,x));
double(subs(f_2,x,-2));
double(subs(f_2,x,-1));
double(subs(f_2,x,-0.5));
double(subs(f_2,x,0.5));
double(subs(f_2,x,1));
double(subs(f_2,x,2));


% Step D: Plotting the Function
figure;
ezplot(f,[-4,4])
grid on

%% Ex 2:
% Define the curve and parabola
syms x;
y_curve = sqrt(2 - x^2);
y_par = x^2;

zeros_y_curve = solve(y_curve,x);
zeros_y_Area = solve(y_curve - y_par,x);

% Step A: Draw the region bounded by the curve, the y-axis, and the parabola y = x^2 in the first quadrant.
figure;
fplot(y_curve,[0,1])
hold on;
fplot(y_par,[0,1])
grid on;
hold off;

% Step B: Find the area of this region.

area_region = abs(int(y_curve - y_par, 0,1));
double(area_region)

% Step C: Calculate the volume of the solid generated by rotating the region about the x_axis.

volume_x_axis = pi * int((y_curve - y_par)^2, 0,1);
double(volume_x_axis)

% Step D: Calculate the volume of the solid generated by rotating the region about the y_axis.

volume_y_axis = 2 * pi * int(x * (y_curve - y_par), 0,1);
double(volume_y_axis)
