# -*- coding: utf-8 -*-
"""Systems Analysis and Decision Support Methods

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jzf1aGEsSSVQka3pKRci8jRTi-9RmuYQ

# Class 1
"""

!pip install gurobipy

"""# Class 2

###Problem 1:
Given S={3,4,7,...}, We need to return a subset with the half sum of S
"""

import random
from gurobipy import Model, GRB

s = [random.randint(1, 100) for _ in range(10)]
print("S = " + str(s))
m = Model(name='Problem 1')
P2 = sum(s[i] for i in range(len(s))) / 2
x = m.addVars(len(s), vtype=GRB.BINARY)

m.setObjective(P2 - quicksum(x[i] * s[i] for i in range(len(s)))) # Calculates the minimum including negatives
m.addConstr(P2 - quicksum(x[i] * s[i] for i in range(len(s))) >= 0) #Capes them until 0, so it searches an approach near 0
m.optimize()

subset = [s[i] for i in range(len(s)) if x[i].X > 0.5]
print("Subset 1:", subset)
print("Subset 2:", [v for v in s if v not in subset])

for i in range(len(s)):
    print(f"x[{i}] = {x[i].X}")

"""###Problem 2:
Given P={3,4,7,...}, P={3,4,7,...}, We need given the prices and weights, we need to maximize the price without overpassing the weight.
"""

import random
from gurobipy import Model, GRB

p = [random.randint(1, 50) for _ in range(10)] # Prices
w = [random.randint(1, 50) for _ in range(len(p))] # Weights

MaxW = 50
print("Prices  = " + str(p))
print("Weights = " + str(w))
print("Max Weight = " + str(MaxW))

m = Model(name='Problem 2')
x = m.addVars(len(s), vtype=GRB.BINARY)

m.setObjective(quicksum(x[i] * p[i] for i in range(len(p))), GRB.MAXIMIZE) # Calculates the price
m.addConstr(quicksum(x[i] * w[i] for i in range(len(p))) <= MaxW) #Capes weight until MaxW
m.optimize()

subset = [p[i] for i in range(len(p)) if x[i].X > 0.5]
print("We take:", subset)
print("We leave:", [v for v in p if v not in subset])
print(f"Max Price = {sum(subset)}")
print(f"Capacity = {sum([w[i] for i in range(len(w)) if x[i].X > 0.5])} / {MaxW}")

for i in range(len(p)):
    print(f"x[{i}] = {x[i].X}")

"""###Problem 3:
Given T={3,4,7,...}, M = ..., We need given the times it takes for some tasks, we need to minimize the time for the lastest finishing machine Cmax.
"""

import random
from gurobipy import Model, GRB

t = [random.randint(1, 100) for _ in range(10)]
print("Times = " + str(t))
num_tasks = len(t)
num_machines = 3 # num of machines
print(f"Number of Machines = {num_machines}")

m = Model(name='Problem 3')
x = m.addVars(num_tasks, num_machines, vtype=GRB.BINARY) # Intead of a list we make a matrix of 1/0
Cmax = m.addVar(lb=0, vtype=GRB.INTEGER) # Cmax >= 0, and integer

m.setObjective(Cmax) #It will dinamically be lowered
for j in range(num_machines):
    m.addConstr(quicksum(t[i] * x[i,j] for i in range(num_tasks)) <= Cmax)

for i in range(num_tasks):
  m.addConstr(quicksum(x[i,j] for j in range(num_machines)) == 1) # Each task executed once

m.optimize()

# Print results
print("\nOptimal Makespan:", Cmax.X)
for j in range(num_machines):
    tasks_on_machine = [i for i in range(num_tasks) if x[i,j].X > 0.5]
    times_on_machine = [t[i] for i in tasks_on_machine]
    print(f"Machine {j+1}: Tasks {tasks_on_machine} with times {times_on_machine}, total = {sum(times_on_machine)}")

"""# Class 3

###Problem 1:
Given T={1,2,3,4,...} (Triangle IDs), D={1,2,3,...} (Dot IDs), C={3,4,7,...} where Ci = cost of Ti, d={{5,2,15},{5,7,8},{64,2,4},{7,5,9}} (Example 3 triangles, 4 dots) where dij = distance between Ti and Dj. And a cost bound (B >= sum(T selected))
"""

import random
from gurobipy import Model, GRB, quicksum

num_triangles = 10
num_dots = 10
B = 100

print(f"Number of Triangles = {num_triangles}")
print(f"Number of Dots = {num_dots}")
print(f"Bound = {B}")

C = [random.randint(1, 100) for _ in range(num_triangles)] # Cost of each triangle
d = [[random.randint(1, 100) for _ in range(num_dots)] for _ in range(num_triangles)] # Distance between each triangle and dot

for i in range(num_triangles):
    print(f"T{i+1:>2} | C: {C[i]:>3} | d: {d[i]}")
print()

m = Model(name='Problem 1')
y = m.addVars(num_triangles, vtype=GRB.BINARY) # Triangles selected
x = m.addVars(num_triangles, num_dots, vtype=GRB.BINARY) # If dot(j) is assigned to tri(i)

# C[i] / d[i,j] / y[i] / x[i,j]
m.setObjective(quicksum(quicksum(d[i][j] * x[i,j] for i in range(num_triangles)) for j in range(num_dots)))

m.addConstr(quicksum(y[i] * C[i] for i in range(num_triangles)) <= B)

for j in range(num_dots):
  m.addConstr(quicksum(x[i,j] for i in range(num_triangles)) == 1) # Each dot has at most/least 1 triangle

for i in range(num_triangles):
    for j in range(num_dots):
        m.addConstr(x[i,j] <= y[i])

m.optimize()

# Print results
if m.status == GRB.OPTIMAL:
    print("\nOptimal Solution Found!\n")

    print("Selected Triangles:")
    for i in range(num_triangles):
        if y[i].x > 0.5:
            print(f"Triangle {i} selected (Cost = {C[i]})")

    print("\nDot Assignments:")
    for j in range(num_dots):
        for i in range(num_triangles):
            if x[i, j].x > 0.5:
                print(f"Dot {j} -> Triangle {i} (Distance = {d[i][j]})")

    print(f"\nTotal Distance (Objective Value): {m.objVal}")
    print(f"\nThe total sum of the triangles cost is {sum(C[i] for i in range(num_triangles) if y[i].x > 0.5)} <= {B} = Bound")
else:
    print("No optimal solution found.")

"""###Problem 2:
Given W={1,2,3,4,...,N} (Workers), J={1,2,3,...,M} (Jobs), C={{5,2,15},{5,7,8},{64,2,4},{7,5,9}} where Cij = cost of job(j), maintained by worker(i). And a cost bound (B >= sum(Cost))

import random
from gurobipy import Model, GRB, quicksum
"""

num_workers = 10
num_jobs = 25
B = 100

print(f"Number of Workers = {num_workers}")
print(f"Number of Jobs = {num_jobs}")
print(f"Bound = {B}")

C = [[random.randint(1, 100) for _ in range(num_jobs)] for _ in range(num_workers)] # Cost between each job and each worker

# Header
print("     " + " ".join(f"job{j+1:>3}" for j in range(num_jobs)))
# Rows
for i, row in enumerate(C):
    print(f"w{i+1:<3} " + " ".join(f"{val:>6}" for val in row))

m = Model(name='Problem 2')

x = m.addVars(num_workers, num_jobs, vtype=GRB.BINARY) # If job(j) is assigned to worker(i)

m.setObjective(sum(sum(x[i,j] for i in range(num_workers)) for j in range(num_jobs)), GRB.MAXIMIZE)

m.addConstr(quicksum(quicksum(x[i,j] * C[i][j] for i in range(num_workers)) for j in range(num_jobs)) <= B)

for j in range(num_jobs):
  m.addConstr(quicksum(x[i,j] for i in range(num_workers)) <= 1) # Each job has at most 1 worker
for i in range(num_workers):
  m.addConstr(quicksum(x[i,j] for j in range(num_jobs)) <= 1) # Each worker has at most 1 job

m.optimize()

# Print solution
if m.status == GRB.OPTIMAL:
    print("\nOptimal assignment:\n")

    total_cost = 0
    total_jobs = 0

    for i in range(num_workers):
        for j in range(num_jobs):
            if x[i, j].X > 0.5:  # variable is 1
                print(f"Worker w{i+1:<2} -> Job job{j+1:<2}  (Cost = {C[i][j]:<3})")
                total_cost += C[i][j]
                total_jobs += 1

    print("\nSummary:")
    print(f"Total assigned jobs = {total_jobs}")
    print(f"Total cost = {total_cost} <= {B} = Bound")

"""# Class 4

###Problem 1:
Given Lmax=the length of a rope and L={2,1.5,3,...} (Lengths of subropes), N={10,45,13,...} (Money you earn per L of subropes). Maximize the Profit sum(N) given that sum(selected L) <= Lmax
"""

import random
from gurobipy import Model, GRB, quicksum

Lmax = 235 # Length of the rope
L = [random.randint(1, 100) for _ in range(10)] # Lengths of subropes
N = [random.randint(1, 100) for _ in range(len(L))] # Money you earn per L of subropes

print(f"Length of rope = {Lmax}")
for i in range(len(L)):
    print(f"L_sub: {L[i]:>3} | N: {N[i]:>3}")
print()

m = Model(name='Problem 1')
L_quantity = m.addVars(len(L), vtype=GRB.INTEGER) # Subropes selected

# Lmax, L[i], N[i], L_bin[i]
m.setObjective(quicksum(L_quantity[i] * N[i] for i in range(len(L))), GRB.MAXIMIZE) # Selected lenth * price

m.addConstr(quicksum(L[i] * L_quantity[i] for i in range(len(L))) <= Lmax)

for i in range(len(L)):
  m.addConstr(L_quantity[i] >= 0) # Minimum of 0 for quantity

for i in range(len(L)):
  m.addConstr(L[i] * L_quantity[i] <= Lmax) # Max of Length for every length

m.optimize()

# Print results
print("\nOptimal solution:")
total_length = 0
total_profit = 0

for i in range(len(L)):
    qty = L_quantity[i].X  # optimized value
    if qty > 0:
        print(f"Type {i}: L = {L[i]}, N = {N[i]}, Quantity = {int(qty)}")
        total_length += L[i] * qty
        total_profit += N[i] * qty

print(f"\nTotal used length = {total_length}")
print(f"Total profit = {total_profit}")
print(f"Remaining rope = {Lmax - total_length}")

"""###Problem 2:
Subset sum: Given Sm={2,1.5,3,...} (Main subset), Si={10,45,13,...} (Any subset of subset). The union of several Si must cover (not be equal, just include all the Sm by union of Si).
"""

import random
from gurobipy import Model, GRB, quicksum

NumberSubsets = 12

S = []
for _ in range(NumberSubsets):
    S.append(set(random.randint(1, 100) for _ in range(9)))

all_elements = set().union(*S)
Sm = set(random.sample(list(all_elements), 15))

print(f"Main set = {Sm}")
for i in range(len(S)):
    print(f"Subset {i:>2}: {S[i]}")
print()

m = Model(name='Problem 2')

x = m.addVars(len(S), vtype=GRB.BINARY)

m.setObjective(sum(x[i] for i in range(len(S))), GRB.MINIMIZE)

for e in Sm:
    m.addConstr(sum(x[i] for i in range(len(S)) if e in S[i]) >= 1)

m.optimize()

# Print results
if m.Status == GRB.OPTIMAL:
    for i in range(len(S)):
        if x[i].X > 0.5:
            print(f"Subset {i}: {S[i]}")
else:
    print("Model not optimal. Status:", m.Status)

"""###Problem 3:
Given P={2,1.5,3,...} (Time for completing job i), N={10,45,50,...} (Min Releasing time of Job i).
The last job must finish the earlier.
"""

import random
from gurobipy import Model, GRB, quicksum

NumberJobs = 10

P = [random.randint(1, 100) for _ in range(NumberJobs)]

N = [0]
for i in range(1, NumberJobs):
    N.append(N[i-1] + random.randint(1, 100))

m = Model("Problem_3")

Cmax = m.addVar(lb=0, vtype=GRB.CONTINUOUS)
S = m.addVars(NumberJobs, lb=0, vtype=GRB.CONTINUOUS)
C = m.addVars(NumberJobs, lb=0, vtype=GRB.CONTINUOUS)

x = m.addVars(NumberJobs, NumberJobs, vtype=GRB.BINARY)

m.setObjective(Cmax, GRB.MINIMIZE)

M = sum(P) + max(N)

for j in range(NumberJobs):
    m.addConstr(C[j] == S[j] + P[j])
    m.addConstr(S[j] >= N[j])
    m.addConstr(Cmax >= C[j])

for i in range(NumberJobs):
    for j in range(NumberJobs):
        if i != j:
            m.addConstr(S[i] >= C[j] - M * (1 - x[i, j]))
            m.addConstr(S[j] >= C[i] - M * x[i, j])
            m.addConstr(x[i, j] + x[j, i] == 1)

m.optimize()

# Print results
if m.status == GRB.OPTIMAL:
    print("Cmax:", Cmax.x)
    for j in range(NumberJobs):
        print(f"Job {j}: Start={S[j].x}, Completion={C[j].x}, Release={N[j]}, Processing={P[j]}")

"""# Class 5

Report in Latex 2 caras max (1 hoja por las 2 caras)
1. Find a Problem (decision variables, problem in mathematical form)
2. Metaheuristic (Nature inspired algorithm) (simulated annealing, tabu search, ant colony optimisation, bacterial foraging optimization)
2.1 Time complexity, memory complexity
3. Table:
1.Results obtained by guroby | 2.Results obtained by Metaheuristic
....|....
....|....

...
How the guroby is better than the metaheuristic

/+ the code solving the problem in guroby and the metaheuristic

Mi idea es crear dada una red de clientes que necesitan wifi, tenemos que llenar la ciudad de repetidores dado que mínimo cada repetidor está conectado con otro, cada zona de la ciudad cuesta x, y que cada cliente en el mapa, tenga mínimo 1 repetidor a mano. Calcular la posición en la cual irán los repetidores y el costo de cada uno, además de la rentabilidad de cada repetidor / de cliente.
"""